// Keeps only the Windows desktop icons generated by `tauri icon`, removing
// the Android / iOS / Windows Store / macOS extras. daytasks is a portable
// Windows app; regenerate the full set later if that ever changes.
import { readdirSync, rmSync } from "node:fs";

const KEEP = new Set(["32x32.png", "128x128.png", "128x128@2x.png", "icon.ico"]);
const dir = "src-tauri/icons";

for (const entry of readdirSync(dir, { withFileTypes: true })) {
  const name = entry.name;
  if (entry.isDirectory()) {
    rmSync(`${dir}/${name}`, { recursive: true, force: true });
  } else if (!KEEP.has(name)) {
    rmSync(`${dir}/${name}`, { force: true });
  }
}

console.log(`pruned src-tauri/icons, keeping: ${[...KEEP].join(", ")}`);
