// Keeps only the Windows desktop icons generated by `tauri icon` for the
// light and dark variants, removing the Android / iOS / Windows Store / macOS
// extras. daytasks is a portable Windows app; regenerate the full set later
// if that ever changes.
import { readdirSync, rmSync } from "node:fs";

const VARIANTS = ["light", "dark"];
const KEEP = new Set(["32x32.png", "128x128.png", "128x128@2x.png", "icon.ico"]);
const dir = "src-tauri/icons";

for (const variant of VARIANTS) {
  const vdir = `${dir}/${variant}`;
  for (const entry of readdirSync(vdir, { withFileTypes: true })) {
    const path = `${vdir}/${entry.name}`;
    if (entry.isDirectory()) {
      rmSync(path, { recursive: true, force: true });
    } else if (!KEEP.has(entry.name)) {
      rmSync(path, { force: true });
    }
  }
}

// Top level: only the variant directories may exist.
for (const entry of readdirSync(dir, { withFileTypes: true })) {
  if (!VARIANTS.includes(entry.name)) {
    rmSync(`${dir}/${entry.name}`, { recursive: true, force: true });
  }
}

console.log(
  `pruned ${dir}, keeping per variant (${VARIANTS.join(", ")}): ${[...KEEP].join(", ")}`,
);
